// Generated by meta.macro
import LoginPage from '~/pages/compile/LoginPage.js';
import HomePage from '~/pages/compile/HomePage.js';
import Loadable from 'react-loadable';
import Loading from './Loading';

const lazy = loader =>
  Loadable({
    delay: 400,
    loading: Loading,
    loader
  });
const rootConfig = [
  {
    path: '/detail',
    component: lazy(() =>
      import(/* webpackChunkName: "common" */ '~/pages/compile/DetailPage.js')
    )
  },
  {
    path: '/login',
    component: LoginPage
  },
  {
    path: '/home',
    component: HomePage
  }
];

export default rootConfig;
