// Generated by meta.macro
import LoginPage from '~/pages/compile/LoginPage.js';
import HomePage from '~/pages/compile/HomePage.js';
import Detail2Page from '~/pages/compile/Detail2Page.js';

const rootConfig = [
  {
    path: '/login',
    component: LoginPage
  },
  {
    path: '/home',
    component: HomePage
  },
  {
    path: '/detail',
    component: Detail2Page
  }
];

export default rootConfig;
